/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const Hotline = t.iface([], {
  "pref_ja": "string",
  "pref_en": "string",
  "center_ja": "string",
  "center_en": "string",
  "phone": "string",
  "lang": "string",
  "hours": "string",
  "postal_code": t.opt("string"),
  "address": t.opt("string"),
  "url": "string",
  "comments": t.opt("string"),
  "topics": t.opt("string"),
  "hotline": t.opt("string"),
});

export const LangProps = t.iface([], {
  "lang": "string",
});

export const TxProps = t.iface([], {
  "lang": "string",
  "tx": t.func("string", t.param("_", "string")),
});

const exportedTypeSuite: t.ITypeSuite = {
  Hotline,
  LangProps,
  TxProps,
};
export default exportedTypeSuite;
