/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const Hotline = t.iface([], {
  "pref_ja": "string",
  "pref_en": "string",
  "center_ja": "string",
  "center_en": "string",
  "phone": "string",
  "lang": "string",
  "hours": "string",
  "postal_code": t.opt(t.union("string", "undefined")),
  "address": t.opt(t.union("string", "undefined")),
  "url": "string",
  "comments": t.opt(t.union("string", "undefined")),
  "topics": t.opt(t.union("string", "undefined")),
  "hotline": t.opt(t.union("string", "undefined")),
});

export const Row = t.array("string");

export const CSV = t.array("Row");

const exportedTypeSuite: t.ITypeSuite = {
  Hotline,
  Row,
  CSV,
};
export default exportedTypeSuite;
